services:
  app:
    build: .
    network_mode: host
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor
    command: php artisan serve --host=0.0.0.0 --port=8000

volumes:
  vendor: